# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['docker_host:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['docker_host:8080']

  - job_name: 'postgres_school_db'
    static_configs:
      - targets: ['postgres_exporter_school_db:9187']

  - job_name: 'postgres_skeduler_db'
    static_configs:
      - targets: ['postgres_exporter_skeduler_db:9187']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
